In [221]:
import numpy as np

def pagerank(M, eps=1.0e-9, d=0.85):
    N = M.shape[1]
    v1 = [[100],[2],[3],[4],[5]]
    
    v1 = v1 / np.linalg.norm(v1, 1)
    v = v1
    last_v = np.ones((N, 1), dtype=np.float32) * 100
    
    for _ in range(100):
        v = np.matmul(M, v)
        
    print (v)
        
    v = v * v1
    v = v / np.linalg.norm(v, 1)
    return v

M = np.array([[0.99, 0.0, 0.0, 0.1, 0.00],
              [0.0, 0.5, 0.4, 0.3, 0.0],
              [0.0, 0.0, 0.5, 0.0, 0.5],
              [0.0, 0.3, 0.0, 0.5, 0.0],
              [0.01, 0.2, 0.1, 0.1, 0.5]])

v = pagerank(M, 0.001, 0.85)

print (v)
print (sum(v))


[[0.66144635]
 [0.10558287]
 [0.08480557]
 [0.06322416]
 [0.08494106]]
[[0.98301053]
 [0.00313825]
 [0.00378102]
 [0.00375843]
 [0.00631177]]
[1.]


In [209]:
a = np.random.rand(2,2)
row_sums = a.sum(axis=1)
new_matrix = a / row_sums[:, np.newaxis]
print (new_matrix)

[[0.21969214 0.78030786]
 [0.45932456 0.54067544]]


In [222]:



class bittensor:
    
    def __init__(self):
        self.S = {} # id --> stake
        self.W = {} # id --> weight
        self.A = {} # id --> attr
        
    def insert(self, id):
        self.S[id] = 0
        self.W[id] = {}
        self.A[id] = 0
        
    def set_stake(self, id, stake):
        self.S[id] = stake
        self.supply = sum(self.S.values())
        
    def set_weights(self, id, weights):
        assert( sum(weights.values()) == 1.0 )
        self.W[id] = weights
    
    def update(self):
        
        




SyntaxError: unexpected EOF while parsing (<ipython-input-222-75519974130e>, line 6)