In [429]:
import numpy as np

def pagerank(M):    
    v = [[0.5],[0.5]]
    v = v / np.linalg.norm(v, 1)
    
    for _ in range(1000):
        v = np.matmul(M, v)
        print (v)
        
    v = v / np.linalg.norm(v, 1)
    return v

M = np.array([[0.99, 0.02],
              [0.01, 0.98]])

v = pagerank(M)

print (v)
print (sum(v))


[[0.505]
 [0.495]]
[[0.50985]
 [0.49015]]
[[0.5145545]
 [0.4854455]]
[[0.51911787]
 [0.48088213]]
[[0.52354433]
 [0.47645567]]
[[0.527838]
 [0.472162]]
[[0.53200286]
 [0.46799714]]
[[0.53604277]
 [0.46395723]]
[[0.53996149]
 [0.46003851]]
[[0.54376265]
 [0.45623735]]
[[0.54744977]
 [0.45255023]]
[[0.55102627]
 [0.44897373]]
[[0.55449548]
 [0.44550452]]
[[0.55786062]
 [0.44213938]]
[[0.5611248]
 [0.4388752]]
[[0.56429106]
 [0.43570894]]
[[0.56736233]
 [0.43263767]]
[[0.57034146]
 [0.42965854]]
[[0.57323121]
 [0.42676879]]
[[0.57603428]
 [0.42396572]]
[[0.57875325]
 [0.42124675]]
[[0.58139065]
 [0.41860935]]
[[0.58394893]
 [0.41605107]]
[[0.58643046]
 [0.41356954]]
[[0.58883755]
 [0.41116245]]
[[0.59117242]
 [0.40882758]]
[[0.59343725]
 [0.40656275]]
[[0.59563413]
 [0.40436587]]
[[0.59776511]
 [0.40223489]]
[[0.59983216]
 [0.40016784]]
[[0.60183719]
 [0.39816281]]
[[0.60378207]
 [0.39621793]]
[[0.60566861]
 [0.39433139]]
[[0.60749855]
 [0.39250145]]
[[0.6092736]
 [0.3907264]]
[[0.6109953

In [209]:
a = np.random.rand(2,2)
row_sums = a.sum(axis=1)
new_matrix = a / row_sums[:, np.newaxis]
print (new_matrix)

[[0.21969214 0.78030786]
 [0.45932456 0.54067544]]


In [481]:

import copy 

class Bittensor:
    
    def __init__(self):
        self.S = {} # id --> stake
        self.W = {} # id --> weights (id, w)
        self.A = {} # id --> attr
        self.n = len(self.S.values())
        self.supply = sum(self.S.values())
        
    def insert(self, id, stake=0, weights=[]):
        self.W[id] = weights
        self.S[id] = stake
        self.A[id] = 0
        self.supply = sum(self.S.values())
        
    def _normalize_A(self):
        sum_a = sum(self.A.values())
        for id in self.A.keys():
            if sum_a == 0:
                 self.A[id] = 1 / len(self.A)
            else:
                 self.A[id] = (self.A[id] / sum_a)

    def matmul(self, W, b):
        result = {}
        for id in (W.keys()):
            if len(W[id]) > 1:
                for w in W[id]:
                    if w[0] in result:
                        result[w[0]] += b[id] * w[1]
                    else:
                        result[w[0]] = b[id] * w[1]
        return result
        
    def update(self, steps=100):
        
        self._normalize_A()
        temp = self.A
        for _ in range(steps):
            temp = self.matmul(self.W, temp)              
        self.A = temp      
        self._normalize_A()
                    
    def emit(self):        
        emmission = self.supply * 0.01 + 0.01
        for id in self.A.keys():
            self.S[id] += emmission * self.A[id]

    def __str__(self):
        strng = "" 
        strng += "S: " + str([id + ": %.3f" % self.S[id] for id in self.S.keys()]) + "\n"
        strng += "A: " + str([id + ": %.3f" % self.A[id] for id in self.A.keys()]) + "\n" 
        strng += "W{ \n"
        for id in self.S.keys():
            strng += "\t"
            strng += str(id)
            strng += ": "
            for w in self.W[id]:
                wstr = str(w[0]) + " " + str(w[1])
                strng += wstr
                strng += " "

            strng += "\n"
        strng += '}'
        return strng




In [482]:
b = Bittensor()
b.insert('a', 0, [('a', 0.5), ('b', 0.5)])
b.insert('b', 0, [('b', 0.5), ('a', 0.5)])
b.insert('c', 0, [('c', 0.8), ('b', 0.1), ('a', 0.1)])
b.insert('d', 0, [('d', 0.8), ('c', 0.2)])

for _ in range(1000):
    b.update()
    b.emit()
print (b)


S: ['a: 5.000', 'b: 5.000', 'c: 0.000', 'd: 0.000']
A: ['a: 0.500', 'b: 0.500', 'c: 0.000', 'd: 0.000']
W{ 
	a: a 0.5 b 0.5 
	b: b 0.5 a 0.5 
	c: c 0.8 b 0.1 a 0.1 
	d: d 0.8 c 0.2 
}
